from typing import Optional

"""
Write a function that returns the smallest nonnegative number which can be 
generated by using all the digits with odd values of a given number.

Example: 10430
Result:  13
"""


def rearrange_digits(number: int) -> Optional[int]:
    # Code here
    arr1 = []
    for ind in str(abs(number)):
        if int(ind) % 2 == 1:
            arr1.append(ind)
    if len(arr1)==0:
        return None
    arr2 = ''.join(sorted(arr1))
    return int(arr2)


# Tests
assert (rearrange_digits(690321) == 139)
assert (rearrange_digits(10430) == 13)
assert (rearrange_digits(2024) == None)
assert (rearrange_digits(0) == None)
assert (rearrange_digits(-2) == None)
assert (rearrange_digits(-3) == 3)
assert (rearrange_digits(-58)) == 5
assert (rearrange_digits(-79) == 79)
assert (rearrange_digits(-1717) == 1177)
print("Passed")

# Reference
#    Cast  values:  int(val), str(val)
#    Sort  lists:   val.sort(reverse=False), sorted(val, reverse=False)
#    Split strings: val.split(), list(val)
#    Join  strings: "".join(val)