apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 9000       # Port exposed by the service
      targetPort: 9000 # Port on the container
  type: NodePort