version: 2

sources:
  - name: raw
    schema: raw     # ← this must match the actual schema name in your SQL Server DB
    tables:
      - name: orders
      - name: customers

models:
#  - name: stg_customers
#    description: "Staging model for customers"
#    columns:
#      - name: customer_id
#        description: "Primary key"
#        tests:
#          - not_null
#          - unique

  - name: dim_customers
    description: "Customer dimension table"