name: join_dbt_project
version: 1.0.0

profile: advanced_profile  # Refers to ~/.dbt/profiles.yml

model-paths: ["models"]
#seed-paths: ["seeds"]
#macro-paths: ["macros"]
#snapshot-paths: ["snapshots"]
#test-paths: ["tests"]

models:
  join_dbt_project:
    staging:
      materialized: view
    marts:
      materialized: table